---
platform: linux

image_resource: 
  type: docker-image
  source:
    repository: alpine

inputs: 
- name: source
- name: om-release

outputs:
- name: releases

run: 
  path: /bin/sh
  args: ["source/ci/scripts/copy-release.sh"]
