---
platform: linux

image_resource: 
  type: docker-image
  source:
    repository: public.ecr.aws/bacardi/alpine
    tag: 3.13.0

inputs: 
- name: source
- name: om-release
- name: bosh-release
- name: pivnet-release
- name: helm-release
- name: kapp-release
- name: ytt-release
- name: kp-release

outputs:
- name: releases

run: 
  path: /bin/sh
  args: ["source/ci/scripts/copy-release.sh"]
