---
platform: linux

image_resource: 
  type: docker-image
  source:
    repository: ubuntu
    tag: 18.04

inputs: 
- name: source
- name: om-release
- name: bosh-release
- name: pivnet-release
- name: helm-release

outputs:
- name: releases

run: 
  path: /bin/sh
  args: ["source/ci/scripts/copy-release.sh"]
