---
resource_types:
  - name: email
    type: docker-image
    source:
      repository: pcfseceng/email-resource

  - name: pivnet
    type: docker-image
    source:
      repository: pivotalcf/pivnet-resource
      tag: v2.0.1

resources:
  - name: source
    type: git
    icon: github-circle
    check_every: 10m 
    source:
      uri: https://github.com/devulrix/t-dev-container.git
      branch: master

  - name: om-release
    type: github-release
    icon: github-circle
    check_every: 110m 
    source:
      owner: pivotal-cf
      repository: om
      access_token: ((gh-token))

  - name: bosh-release
    type: github-release
    icon: github-circle
    check_every: 120m 
    source:
      owner: cloudfoundry
      repository: bosh-cli
      access_token: ((gh-token))

  - name: pivnet-release
    type: github-release
    icon: github-circle
    check_every: 120m 
    source:
      owner: pivotal-cf
      repository: pivnet-cli
      access_token: ((gh-token))

  - name: helm-release
    type: github-release
    icon: github-circle
    check_every: 130m 
    source:
      owner: helm
      repository: helm
      access_token: ((gh-token))

  - name: ytt-release
    type: github-release
    icon: github-circle
    check_every: 130m 
    source:
      owner: vmware-tanzu
      repository: carvel-ytt
      access_token: ((gh-token))

  - name: kapp-release
    type: github-release
    icon: github-circle
    check_every: 130m 
    source:
      owner: vmware-tanzu
      repository: carvel-kapp
      access_token: ((gh-token))

  - name: kp-release
    type: pivnet
    source:
      api_token: ((api-token))
      product_slug: build-service
      product_version: 1.0.4
      #--product-file-id=817470

  - name: t-image
    type: docker-image
    icon: docker
    source:
      username: ((docker-user))
      password: ((docker-password))
      repository: ((docker-repo))/t-image
      tag: 1.0     

jobs:
- name: build-container
  plan:
  - get: source
    trigger: true
  - get: om-release
    trigger: true
    params:
      globs: 
      - om-linux* 
  - get: bosh-release
    trigger: true
  - get: pivnet-release
    trigger: true
    params:
      globs: 
      - pivnet-linux-amd64-* 
  - get: helm-release
    trigger: true
    params:
      globs:
      - helm*-linux-amd64.tar.gz
  - get: ytt-release
    trigger: true
    params:
      globs:
      - ytt-linux-amd64*
  - get: kapp-release
    trigger: true
    params:
      globs:
      - kapp-linux-amd*
  - get: kp-release
    params:
      globs:
      - kp-linux*
  - task: copy-release
    file: source/ci/tasks/copy-release.yml
  - put: t-image
    params:
          build: ./releases
          tag_as_latest: true