---
resource_types:
  - name: email
    type: docker-image
    source:
      repository: pcfseceng/email-resource

resources:
  - name: source
    type: git
    icon: github-circle
    check_every: 10m 
    source:
      uri: https://github.com/devulrix/t-dev-container.git
      branch: master

  - name: om-release
    type: github-release
    icon: github-circle
    check_every: 110m 
    source:
      owner: pivotal-cf
      repository: om

  - name: bosh-release
    type: github-release
    icon: github-circle
    check_every: 120m 
    source:
      owner: cloudfoundry
      repository: bosh-cli

  - name: pivnet-release
    type: github-release
    icon: github-circle
    check_every: 120m 
    source:
      owner: pivotal-cf
      repository: pivnet-cli

  - name: helm-release
    type: github-release
    icon: github-circle
    check_every: 130m 
    source:
      owner: helm
      repository: helm

  - name: t-image
    type: docker-image
    icon: docker
    source:
      username: ((docker-user))
      password: ((docker-password))
      repository: ((docker-repo))/t-image

jobs:
- name: build-container
  plan:
  - get: source
    trigger: true
  - get: om-release
    trigger: true
    params:
      globs: 
      - om-linux* 
  - get: bosh-release
    trigger: true
  - get: pivnet-release
    trigger: true
    params:
      globs: 
      - pivnet-linux-amd64-* 
  - get: helm-release
    trigger: true
  - task: copy-release
    file: source/ci/tasks/copy-release.yml
  - put: t-image
    params:
          build: ./releases
          tag_as_latest: true

