---
resource_types:
  - name: email
    type: docker-image
    source:
      repository: pcfseceng/email-resource

resources:
  - name: source
    type: git
    icon: github-circle
    check_every: 10m 
    source:
      uri: https://github.com/devulrix/t-dev-container.git
      branch: master

  - name: om-release
    type: github-release
    icon: github-circle
    check_every: 10m 
    source:
      owner: pivotal-cf
      repository: om

  - name: t-image
    type: docker-image
    source:
      username: ((docker-user))
      password: ((docker-password))
      repository: ((docker-repo))/t-image

jobs:
- name: build-container
  plan:
  - get: source
    trigger: true
  - get: om-release
    trigger: true
    params:
      globs: 
      - om-linux* 
  - task: copy-release
    file: source/copy-release.yml
  - put: t-image
    params:
          build: ./source 
          tag_as_latest: true

